import type { ReadyFileTipo } from './ready-files/parseReadyFile';

export type SpitchType = 'company' | 'patient';

export interface Company {
  id: string;
  name: string;
  ruc: string;
  email: string;
}

export interface Patient {
  id: string;
  companyId: string;
  name: string;
  dni: string;
  files: PatientFile[];
}

export interface PatientFile {
  id: string;
  patientId: string;
  name: string;
  type: string;
  size: number;
}

/**
 * Send-payload entity for the email attachment pipeline.
 *
 * `PatientFile` is the display entity (no LAN location). `SelectedFileRef`
 * carries the location triple (`ruc`/`dni`/`idAten`) plus the relative
 * `path` (folder under the patient root; `''` = root) and `name` (file
 * basename) that `IFileRepository.read(ruc, dni, idAten, path, name)`
 * needs to stream the real bytes from the UNC share.
 *
 * Distinct from `PatientFile` by design — adding fields to `PatientFile`
 * is risky because it's a display entity consumed by `EmailEditor` UI.
 * This entity is consumed only by the email-send pipeline.
 */
export interface SelectedFileRef {
  ruc: string;
  dni: string;
  idAten: string;
  path: string;
  name: string;
  /**
   * Optional exam type. Set by the envio wizard when the user picks a
   * specific CAMO, EMO or ADICIONAL file per patient; the send-pipeline
   * rename (`renameReadyFile`) prefers this value over the type inferred
   * from `name` via `parseReadyFile`. `'ADICIONAL'` (ADICIONALES
   * orders) arrives ONLY via this explicit signal — `parseReadyFile`
   * never infers it. Legacy call sites (e.g. per-row `Ver Archivos`
   * flow) omit it — the pipeline falls back to `parseReadyFile(ref.name)`.
   */
  tipoExamen?: ReadyFileTipo;
  /**
   * Optional per-ref patient full name. Stamped by the envio wizard
   * bridge (`buildEmailViewDataFromWizard`) with the resolved
   * patient's name so multi-patient batches produce per-patient
   * attachment names; the send-pipeline rename (`renameReadyFile`)
   * prefers this value over the request-level scalar. Absent or
   * empty (post-trim) falls back to the request-level
   * `nombreCompleto` (legacy callers unchanged).
   */
  nombreCompleto?: string;
}

export interface Spitch {
  id: string;
  /**
   * The area this spitch belongs to (e.g. `'consolidados'`). PR 4 of
   * the email-template-editor change adds the field so the empty-state
   * UX can derive the right editor link from the area. Populated by
   * the `Template → SpitchDTO` boundary projection at
   * `/api/plantillas`. Decision b (design).
   */
  area: string;
  type: SpitchType;
  name: string;
  subject: string;
  bodyHtml: string;
}

export interface EmailAttachment {
  filename: string;
  content: Buffer | string;
  contentType?: string;
}

/**
 * Input shape for a local file dropped from the OS and attached to an
 * email alongside `SelectedFileRef` entries from the LAN share. Carries
 * the file bytes directly (no ruc/dni/idAten coordinates).
 */
export interface LocalAttachmentInput {
  filename: string;
  contentType: string;
  content: Buffer;
}

// ---- Consolidated send history (historial-envios-consolidados) ----

/** Lifecycle status of a history row (`dbo.envios_consolidados` CHECK constraint). */
export type EnvioSendStatus = 'pendiente' | 'enviado' | 'error';

/**
 * Per-attachment snapshot persisted on the history row
 * (`attachmentsJson`). UNC refs keep their durable LAN address plus
 * both the stored and the delivery (renamed) file name; local drops
 * keep metadata only — attachment bytes are never persisted.
 */
export type EnvioAttachmentSnapshot =
  | {
      source: 'unc';
      ruc: string;
      dni: string;
      idAten: string;
      path: string;
      storedName: string;
      deliveryName: string;
      tipoExamen?: ReadyFileTipo;
      nombreCompleto?: string;
    }
  | {
      source: 'local';
      storedName: string;
      contentType: string;
      sizeBytes: number;
    };

/**
 * Write-side payload for `IEnvioHistoryRepository.insert`. The `id`
 * and `sentAt` are generated by the adapter / DB default
 * (`SYSUTCDATETIME()`); the precomputed accent-stripped search
 * columns are derived by the adapter from this payload.
 */
export interface EnvioHistoryInsert {
  status: EnvioSendStatus;
  sentBy: string;
  destino: string;
  companyId: string;
  companyName: string;
  nombreCompleto: string;
  toRecipients: string[];
  ccRecipients: string[];
  subject: string;
  bodyHtml: string;
  attachments: EnvioAttachmentSnapshot[];
}

/** Full history row as read back (dates ISO 8601, JSON columns parsed). */
export interface EnvioHistoryRow {
  id: string;
  sentAt: string;
  status: EnvioSendStatus;
  errorDetail: string | null;
  sentBy: string;
  destino: string;
  companyId: string;
  companyName: string;
  nombreCompleto: string;
  toRecipients: string[];
  ccRecipients: string[];
  subject: string;
  bodyHtml: string;
  attachments: EnvioAttachmentSnapshot[];
}

/** List-view row: `EnvioHistoryRow` without `bodyHtml` (off-row LOB, PK-seek only). */
export type EnvioHistorySummary = Omit<EnvioHistoryRow, 'bodyHtml'>;

/** Paged search input; `fechaInicio`/`fechaFin` are `YYYY-MM-DD` strings. */
export interface EnvioSearchQuery {
  q?: string;
  fechaInicio?: string;
  fechaFin?: string;
  page: number;
}

/** Paged search output (`pageSize` is fixed at 20 by the adapter). */
export interface EnvioSearchResult {
  rows: EnvioHistorySummary[];
  total: number;
  page: number;
}
